#!/usr/bin/env bash

set -euo pipefail

BASE_URL="${1:-http://127.0.0.1:8088}"

routes=(
  "/"
  "/venues.php"
  "/vendors.php"
  "/privacy.php"
  "/terms.php"
  "/cancellation.php"
  "/compare.php"
  "/search.php?q=Jaipur"
  "/seo-landing.php?type=venues&city=jaipur"
  "/seo-landing.php?type=vendors&city=jaipur&category=photography-films"
  "/real-weddings.php"
  "/submit-wedding.php"
  "/event.php?type=Wedding"
  "/city.php?city=Jaipur"
  "/cities.php"
  "/cities.php?q=Mumbai"
  "/cities.php?q=NotListed"
  "/blog.php"
  "/article.php?id=jaipur-venues"
  "/planner.php"
  "/invites.php"
  "/register.php?role=host"
  "/register.php?role=vendor"
  "/register.php?role=venue"
  "/login.php?role=host"
  "/login.php?role=vendor"
  "/login.php?role=venue"
  "/crm/customer/index.php"
  "/crm/customer/recommendations.php"
  "/crm/customer/timeline.php"
  "/crm/customer/moodboards.php"
  "/crm/customer/collaborators.php"
  "/crm/customer/finances.php"
  "/crm/customer/notifications.php"
  "/crm/customer/recent.php"
  "/crm/customer/venue-plan-payment.php"
  "/crm/vendor/index.php"
  "/crm/vendor/availability.php"
  "/crm/vendor/quotes.php"
  "/crm/vendor/reviews.php"
  "/crm/vendor/analytics.php"
  "/crm/vendor/notifications.php"
  "/crm/vendor/subscription.php"
  "/crm/venue/index.php"
  "/crm/venue/leads.php"
  "/crm/venue/leads-new.php"
  "/crm/venue/leads-followups.php"
  "/crm/venue/leads-site-visits.php"
  "/crm/venue/leads-lost.php"
  "/crm/venue/functions.php"
  "/crm/venue/functions-upcoming.php"
  "/crm/venue/functions-calendar.php"
  "/crm/venue/bookings.php"
  "/crm/venue/payments.php"
  "/crm/venue/reports.php"
  "/crm/venue/availability.php"
  "/crm/venue/quotes.php"
  "/crm/venue/reviews.php"
  "/crm/venue/analytics.php"
  "/crm/venue/notifications.php"
  "/crm/venue/subscription.php"
  "/admin/login.php"
  "/admin/index.php"
  "/admin/leads.php"
  "/admin/leads-new.php"
  "/admin/leads-followups.php"
  "/admin/leads-site-visits.php"
  "/admin/leads-lost.php"
  "/admin/functions.php"
  "/admin/functions-upcoming.php"
  "/admin/functions-calendar.php"
  "/admin/bookings.php"
  "/admin/payments.php"
  "/admin/invoices.php"
  "/admin/refunds.php"
  "/admin/commission.php"
  "/admin/customers.php"
  "/admin/venues.php"
  "/admin/venues-active.php"
  "/admin/venues-inactive.php"
  "/admin/vendors.php"
  "/admin/vendors-active.php"
  "/admin/reports.php"
  "/admin/website-cities.php"
  "/admin/website-categories.php"
  "/admin/website-venues.php"
  "/admin/website-blogs.php"
  "/admin/team.php"
  "/admin/reviews.php"
  "/admin/venue-plans.php"
  "/admin/subscriptions.php"
  "/admin/wedding-submissions.php"
  "/admin/notifications.php"
  "/manifest.webmanifest"
  "/offline.html"
  "/sw.js"
  "/sitemap.php"
)

for route in "${routes[@]}"; do
  echo "Checking ${route}"

  curl     --fail     --silent     --show-error     --location     "${BASE_URL}${route}"     > /tmp/wz-response.txt

  if [[ ! -s /tmp/wz-response.txt ]]; then
    echo "Empty response for ${route}"
    exit 1
  fi
done

curl   --fail   --silent   --show-error   --header "X-WZ-Health-Token: ci-health-token"   "${BASE_URL}/api/health.php"   | grep '"ok":true'

echo "Wedding Za HTTP smoke tests passed."
